### ISSUE TITLE
Support for includes

### ISSUE THREAD

**Issue by pztrn** [biozz/sublime-taskfile#4]
Plugin is missing support for [includes](https://taskfile.dev/#/usage?id=including-other-taskfiles).

**Comment by biozz** [comment]
Hi @pztrn! I added support for includes in [v0.8.0](https://github.com/biozz/sublime-taskfile/releases/tag/v0.8.0). It is going to be available on Package Control soon. Please let me know if it works for you. This release ended up with quite a few changes. 😅

Please note, there is an open issue in Taskfile repo go-task/task/issues/603 and if you have `label` keys in your tasks definition it will not work for these tasks. I plan to submit a PR for that issue, because it looks simple.
